import dotenv from "dotenv";
import { connectDB } from "../lib/db.js";
import Problem from "../models/Problem.js";

dotenv.config();

const problems = [
  {
    title: "Meeting Rooms",
    slug: "meeting-rooms",
    difficulty: "Easy",
    category: "Greedy • Intervals",
    description: { text: "Given an array of meeting time intervals, determine if a person can attend all meetings without overlap.", notes: ["Sort intervals by start time." ] },
    tags: ["greedy", "intervals", "arrays"],
    testCases: { javascript: `const intervals = [[0,30],[5,10],[15,20]];\nconsole.log(canAttendMeetings(intervals));`, python: "intervals = [[0,30],[5,10],[15,20]]\nprint(canAttendMeetings(intervals))", java: "int[][] intervals = {{0,30},{5,10},{15,20}};" },
    examples: [{ input: "intervals = [[0,30],[5,10],[15,20]]", output: "false" }],
    constraints: ["1 ≤ intervals.length ≤ 10⁵"],
    starterCode: { javascript: `function canAttendMeetings(intervals) {\n  // Write your solution here\n}`, python: `def canAttendMeetings(intervals):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static boolean canAttendMeetings(int[][] intervals) {\n        // Write your solution here\n        return false;\n    }\n}` },
    expectedOutput: { javascript: "false", python: "False", java: "false" },
  },
  {
    title: "Rotate Image",
    slug: "rotate-image",
    difficulty: "Medium",
    category: "Matrix • Arrays",
    description: { text: "Rotate an n x n matrix clockwise by 90 degrees in place.", notes: ["Use a transpose and reverse approach."] },
    tags: ["matrix", "arrays"],
    testCases: { javascript: `const matrix = [[1,2,3],[4,5,6],[7,8,9]];\nrotate(matrix);\nconsole.log(matrix);`, python: "matrix = [[1,2,3],[4,5,6],[7,8,9]]\nrotate(matrix)\nprint(matrix)", java: "int[][] matrix = {{1,2,3},{4,5,6},{7,8,9}};" },
    examples: [{ input: "matrix = [[1,2,3],[4,5,6],[7,8,9]]", output: "[[7,4,1],[8,5,2],[9,6,3]]" }],
    constraints: ["1 ≤ matrix.length ≤ 20"],
    starterCode: { javascript: `function rotate(matrix) {\n  // Write your solution here\n}`, python: `def rotate(matrix):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static void rotate(int[][] matrix) {\n        // Write your solution here\n    }\n}` },
    expectedOutput: { javascript: "[[7,4,1],[8,5,2],[9,6,3]]", python: "[[7, 4, 1], [8, 5, 2], [9, 6, 3]]", java: "[[7,4,1],[8,5,2],[9,6,3]]" },
  },
  {
    title: "Product of Array Except Self",
    slug: "product-of-array-except-self",
    difficulty: "Medium",
    category: "Array • Prefix Product",
    description: { text: "Return an array answer such that answer[i] is the product of all elements of nums except nums[i].", notes: ["Do not use division."] },
    tags: ["arrays", "prefix"],
    testCases: { javascript: `const nums = [1,2,3,4];\nconsole.log(productExceptSelf(nums));`, python: "nums = [1,2,3,4]\nprint(productExceptSelf(nums))", java: "int[] nums = {1,2,3,4};" },
    examples: [{ input: "nums = [1,2,3,4]", output: "[24,12,8,6]" }],
    constraints: ["2 ≤ nums.length ≤ 10⁵"],
    starterCode: { javascript: `function productExceptSelf(nums) {\n  // Write your solution here\n}`, python: `def productExceptSelf(nums):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static int[] productExceptSelf(int[] nums) {\n        // Write your solution here\n        return new int[0];\n    }\n}` },
    expectedOutput: { javascript: "[24,12,8,6]", python: "[24, 12, 8, 6]", java: "[24,12,8,6]" },
  },
  {
    title: "Container With Most Water",
    slug: "container-with-most-water",
    difficulty: "Medium",
    category: "Two Pointers • Array",
    description: { text: "Find two lines that together with the x-axis form a container that can hold the most water.", notes: ["Use a two-pointer strategy."] },
    tags: ["two-pointers", "arrays"],
    testCases: { javascript: `const height = [1,8,6,2,5,4,8,3,7];\nconsole.log(maxArea(height));`, python: "height = [1,8,6,2,5,4,8,3,7]\nprint(maxArea(height))", java: "int[] height = {1,8,6,2,5,4,8,3,7};" },
    examples: [{ input: "height = [1,8,6,2,5,4,8,3,7]", output: "49" }],
    constraints: ["n == height.length", "2 ≤ n ≤ 10⁵"],
    starterCode: { javascript: `function maxArea(height) {\n  // Write your solution here\n}`, python: `def maxArea(height):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static int maxArea(int[] height) {\n        // Write your solution here\n        return 0;\n    }\n}` },
    expectedOutput: { javascript: "49", python: "49", java: "49" },
  },
  {
    title: "Longest Substring Without Repeating Characters",
    slug: "longest-substring-without-repeating-characters",
    difficulty: "Medium",
    category: "String • Sliding Window",
    description: { text: "Find the length of the longest substring without repeating characters.", notes: ["Use a sliding window and a hash map."] },
    tags: ["strings", "sliding-window"],
    testCases: { javascript: `const s = 'abcabcbb';\nconsole.log(lengthOfLongestSubstring(s));`, python: "s = 'abcabcbb'\nprint(lengthOfLongestSubstring(s))", java: "String s = 'abcabcbb';" },
    examples: [{ input: "s = 'abcabcbb'", output: "3" }],
    constraints: ["0 ≤ s.length ≤ 5 × 10⁴"],
    starterCode: { javascript: `function lengthOfLongestSubstring(s) {\n  // Write your solution here\n}`, python: `def lengthOfLongestSubstring(s):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static int lengthOfLongestSubstring(String s) {\n        // Write your solution here\n        return 0;\n    }\n}` },
    expectedOutput: { javascript: "3", python: "3", java: "3" },
  },
  {
    title: "Longest Palindromic Substring",
    slug: "longest-palindromic-substring",
    difficulty: "Medium",
    category: "String • Dynamic Programming",
    description: { text: "Return the longest palindromic substring in a string.", notes: ["Expand around centers."] },
    tags: ["strings", "dynamic-programming"],
    testCases: { javascript: `const s = 'babad';\nconsole.log(longestPalindrome(s));`, python: "s = 'babad'\nprint(longestPalindrome(s))", java: "String s = 'babad';" },
    examples: [{ input: "s = 'babad'", output: "bab" }],
    constraints: ["1 ≤ s.length ≤ 10³"],
    starterCode: { javascript: `function longestPalindrome(s) {\n  // Write your solution here\n}`, python: `def longestPalindrome(s):\n    // Write your solution here\n    pass`, java: `class Solution {\n    public static String longestPalindrome(String s) {\n        // Write your solution here\n        return "";\n    }\n}` },
    expectedOutput: { javascript: "bab", python: "bab", java: "bab" },
  },
  {
    title: "Group Anagrams",
    slug: "group-anagrams",
    difficulty: "Medium",
    category: "Hash Map • String",
    description: { text: "Group a list of strings by their anagram signatures.", notes: ["Use a character frequency counter as the signature."] },
    tags: ["strings", "hashmap"],
    testCases: { javascript: `const strs = ['eat','tea','tan','ate','nat','bat'];\nconsole.log(groupAnagrams(strs));`, python: "strs = ['eat','tea','tan','ate','nat','bat']\nprint(groupAnagrams(strs))", java: "String[] strs = {'eat','tea','tan','ate','nat','bat'};" },
    examples: [{ input: "strs = ['eat','tea','tan','ate','nat','bat']", output: "[['eat','tea','ate'],['tan','nat'],['bat']]" }],
    constraints: ["1 ≤ strs.length ≤ 10⁴", "0 ≤ strs[i].length ≤ 100"],
    starterCode: { javascript: `function groupAnagrams(strs) {\n  // Write your solution here\n}`, python: `def groupAnagrams(strs):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static List<List<String>> groupAnagrams(String[] strs) {\n        // Write your solution here\n        return new ArrayList<>();\n    }\n}` },
    expectedOutput: { javascript: "[['eat','tea','ate'],['tan','nat'],['bat']]", python: "[['eat','tea','ate'],['tan','nat'],['bat']]", java: "[[eat,tea,ate],[tan,nat],[bat]]" },
  },
  {
    title: "Koko Eating Bananas",
    slug: "koko-eating-bananas",
    difficulty: "Medium",
    category: "Binary Search • Greedy",
    description: { text: "Determine the minimum eating speed that allows Koko to finish all piles of bananas within h hours.", notes: ["Use binary search over speed values."] },
    tags: ["binary-search", "greedy"],
    testCases: { javascript: `const piles = [3,6,7,11,12];\nconst h = 8;\nconsole.log(minEatingSpeed(piles, h));`, python: "piles = [3,6,7,11,12]\nh = 8\nprint(minEatingSpeed(piles, h))", java: "int[] piles = {3,6,7,11,12}; int h = 8;" },
    examples: [{ input: "piles = [3,6,7,11,12], h = 8", output: "4" }],
    constraints: ["1 ≤ piles.length ≤ 10⁵", "1 ≤ h ≤ 10⁹"],
    starterCode: { javascript: `function minEatingSpeed(piles, h) {\n  // Write your solution here\n}`, python: `def minEatingSpeed(piles, h):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static int minEatingSpeed(int[] piles, int h) {\n        // Write your solution here\n        return 0;\n    }\n}` },
    expectedOutput: { javascript: "4", python: "4", java: "4" },
  },
  {
    title: "Median of Two Sorted Arrays",
    slug: "median-of-two-sorted-arrays",
    difficulty: "Hard",
    category: "Binary Search • Arrays",
    description: { text: "Given two sorted arrays of sizes m and n, find the median of the combined sorted arrays.", notes: ["The overall run time should be O(log n)."] },
    tags: ["binary-search", "arrays"],
    testCases: { javascript: `const nums1 = [1,3];\nconst nums2 = [2];\nconsole.log(findMedianSortedArrays(nums1, nums2));`, python: "nums1 = [1,3]\nnums2 = [2]\nprint(findMedianSortedArrays(nums1, nums2))", java: "int[] nums1 = {1,3}; int[] nums2 = {2};" },
    examples: [{ input: "nums1 = [1,3], nums2 = [2]", output: "2.0" }],
    constraints: ["0 ≤ m, n ≤ 10³"],
    starterCode: { javascript: `function findMedianSortedArrays(nums1, nums2) {\n  // Write your solution here\n}`, python: `def findMedianSortedArrays(nums1, nums2):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static double findMedianSortedArrays(int[] nums1, int[] nums2) {\n        // Write your solution here\n        return 0.0;\n    }\n}` },
    expectedOutput: { javascript: "2", python: "2.0", java: "2.0" },
  },
  {
    title: "Word Ladder",
    slug: "word-ladder",
    difficulty: "Medium",
    category: "Graph • Breadth-First Search",
    description: { text: "Return the shortest transformation sequence from beginWord to endWord using a word list.", notes: ["Each transformed word must differ by exactly one character."] },
    tags: ["graph", "bfs", "strings"],
    testCases: { javascript: `const beginWord = 'hit';\nconst endWord = 'cog';\nconst wordList = ['hot','dot','dog','lot','log','cog'];\nconsole.log(ladderLength(beginWord, endWord, wordList));`, python: "beginWord = 'hit'\nendWord = 'cog'\nwordList = ['hot','dot','dog','lot','log','cog']\nprint(ladderLength(beginWord, endWord, wordList))", java: "String beginWord = 'hit'; String endWord = 'cog';" },
    examples: [{ input: "beginWord = 'hit', endWord = 'cog', wordList = ['hot','dot','dog','lot','log','cog']", output: "5" }],
    constraints: ["1 ≤ wordList.length ≤ 5000"],
    starterCode: { javascript: `function ladderLength(beginWord, endWord, wordList) {\n  // Write your solution here\n}`, python: `def ladderLength(beginWord, endWord, wordList):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static int ladderLength(String beginWord, String endWord, List<String> wordList) {\n        // Write your solution here\n        return 0;\n    }\n}` },
    expectedOutput: { javascript: "5", python: "5", java: "5" },
  },
  {
    title: "Lowest Common Ancestor of a Binary Tree",
    slug: "lowest-common-ancestor-of-a-binary-tree",
    difficulty: "Medium",
    category: "Tree • DFS",
    description: { text: "Find the lowest common ancestor of two nodes in a binary tree.", notes: ["Node values are unique."] },
    tags: ["trees", "dfs"],
    testCases: { javascript: `const root = {val:3, left:{val:5}, right:{val:1}};\nconsole.log(lca(root, root.left, root.right));`, python: "root = None\nprint(lca(root, None, None))", java: "TreeNode root = new TreeNode(3);" },
    examples: [{ input: "root = [3,5,1,6,2,0,8,null,null,7,4], p = 5, q = 1", output: "3" }],
    constraints: ["The number of nodes in the tree is in range [2, 10⁵]."],
    starterCode: { javascript: `function lowestCommonAncestor(root, p, q) {\n  // Write your solution here\n}`, python: `def lowestCommonAncestor(root, p, q):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static TreeNode lowestCommonAncestor(TreeNode root, TreeNode p, TreeNode q) {\n        // Write your solution here\n        return null;\n    }\n}` },
    expectedOutput: { javascript: "3", python: "3", java: "3" },
  },
  {
    title: "Invert Binary Tree",
    slug: "invert-binary-tree",
    difficulty: "Easy",
    category: "Tree • Recursion",
    description: { text: "Invert a binary tree by swapping every left and right subtree.", notes: ["The answer is a new tree, not a reference copy."] },
    tags: ["trees", "recursion"],
    examples: [{ input: "root = [4,2,7,1,3,6,9]", output: "[4,7,2,9,6,3,1]" }],
    constraints: ["The number of nodes in the tree is in range [0, 10⁵]."],
    starterCode: { javascript: `function invertTree(root) {\n  // Write your solution here\n}`, python: `def invertTree(root):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static TreeNode invertTree(TreeNode root) {\n        // Write your solution here\n        return null;\n    }\n}` },
    expectedOutput: { javascript: "[4,7,2,9,6,3,1]", python: "[4,7,2,9,6,3,1]", java: "[4,7,2,9,6,3,1]" },
  },
  {
    title: "Binary Search",
    slug: "binary-search",
    difficulty: "Easy",
    category: "Binary Search • Array",
    description: { text: "Given a sorted array, return the index of target if it exists, or -1 otherwise.", notes: ["Use half-open range boundaries."] },
    tags: ["binary-search", "arrays"],
    examples: [{ input: "nums = [-1,0,3,5,9,12], target = 9", output: "4" }],
    constraints: ["1 ≤ nums.length ≤ 10⁵"],
    starterCode: { javascript: `function search(nums, target) {\n  // Write your solution here\n}`, python: `def search(nums, target):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static int search(int[] nums, int target) {\n        // Write your solution here\n        return -1;\n    }\n}` },
    expectedOutput: { javascript: "4", python: "4", java: "4" },
  },
  {
    title: "Sort Colors",
    slug: "sort-colors",
    difficulty: "Medium",
    category: "Array • Dutch National Flag",
    description: { text: "Sort an array of 0, 1, and 2 values in-place.", notes: ["Use three pointers."] },
    tags: ["arrays", "two-pointers"],
    examples: [{ input: "nums = [2,0,2,1,1,0]", output: "[0,0,1,1,2,2]" }],
    constraints: ["n == nums.length", "1 ≤ n ≤ 10⁵"],
    starterCode: { javascript: `function sortColors(nums) {\n  // Write your solution here\n}`, python: `def sortColors(nums):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static void sortColors(int[] nums) {\n        // Write your solution here\n    }\n}` },
    expectedOutput: { javascript: "[0,0,1,1,2,2]", python: "[0, 0, 1, 1, 2, 2]", java: "[0,0,1,1,2,2]" },
  },
  {
    title: "Generate Parentheses",
    slug: "generate-parentheses",
    difficulty: "Medium",
    category: "Backtracking • String",
    description: { text: "Generate all combinations of well-formed parentheses for n pairs.", notes: ["Use recursive backtracking."] },
    tags: ["backtracking", "strings"],
    examples: [{ input: "n = 3", output: "['((()))','(()())','(())()','()(())','()()()']" }],
    constraints: ["1 ≤ n ≤ 8"],
    starterCode: { javascript: `function generateParenthesis(n) {\n  // Write your solution here\n}`, python: `def generateParenthesis(n):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static List<String> generateParenthesis(int n) {\n        // Write your solution here\n        return new ArrayList<>();\n    }\n}` },
    expectedOutput: { javascript: "['((()))','(()())','(())()','()(())','()()()']", python: "['((()))','(()())','(())()','()(())','()()()']", java: "['((()))','(()())','(())()','()(())','()()()']" },
  },
  {
    title: "Minimum Window Substring",
    slug: "minimum-window-substring",
    difficulty: "Hard",
    category: "String • Sliding Window",
    description: { text: "Find the smallest substring in s containing all characters of t.", notes: ["Use a frequency map and sliding window."] },
    tags: ["strings", "sliding-window"],
    examples: [{ input: "s = 'ADOBECODEBANC', t = 'ABC'", output: "BANC" }],
    constraints: ["1 ≤ s.length, t.length ≤ 10⁵"],
    starterCode: { javascript: `function minWindow(s, t) {\n  // Write your solution here\n}`, python: `def minWindow(s, t):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static String minWindow(String s, String t) {\n        // Write your solution here\n        return "";\n    }\n}` },
    expectedOutput: { javascript: "BANC", python: "BANC", java: "BANC" },
  },
  {
    title: "Longest Consecutive Sequence",
    slug: "longest-consecutive-sequence",
    difficulty: "Medium",
    category: "Hash Set • Array",
    description: { text: "Return the length of the longest consecutive sequence of integers in an unsorted array.", notes: ["Use a hash set and only start from the leftmost number of a sequence."] },
    tags: ["hashset", "arrays"],
    examples: [{ input: "nums = [100,4,200,1,3,2]", output: "4" }],
    constraints: ["0 ≤ nums.length ≤ 10⁵"],
    starterCode: { javascript: `function longestConsecutive(nums) {\n  // Write your solution here\n}`, python: `def longestConsecutive(nums):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static int longestConsecutive(int[] nums) {\n        // Write your solution here\n        return 0;\n    }\n}` },
    expectedOutput: { javascript: "4", python: "4", java: "4" },
  },
  {
    title: "Clone Graph",
    slug: "clone-graph",
    difficulty: "Medium",
    category: "Graph • Depth-First Search",
    description: { text: "Return a deep copy of a connected undirected graph.", notes: ["Each node has a val and a list of neighbors."] },
    tags: ["graph", "dfs"],
    examples: [{ input: "node = 1 -> 2 -> 3 -> 1", output: "cloned graph" }],
    constraints: ["The number of nodes is between 0 and 100.", "Node values are unique."],
    starterCode: { javascript: `function cloneGraph(node) {\n  // Write your solution here\n}`, python: `def cloneGraph(node):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static Node cloneGraph(Node node) {\n        // Write your solution here\n        return null;\n    }\n}` },
    expectedOutput: { javascript: "cloned graph", python: "cloned graph", java: "cloned graph" },
  },
  {
    title: "Linked List Cycle",
    slug: "linked-list-cycle",
    difficulty: "Easy",
    category: "Linked List • Two Pointers",
    description: { text: "Determine whether a singly linked list has a cycle.", notes: ["Use Floyd’s tortoise and hare algorithm."] },
    tags: ["linked-list", "two-pointers"],
    examples: [{ input: "head = [3,2,0,-4], pos = 1", output: "true" }],
    constraints: ["0 ≤ pos ≤ n - 1"],
    starterCode: { javascript: `function hasCycle(head) {\n  // Write your solution here\n}`, python: `def hasCycle(head):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static boolean hasCycle(ListNode head) {\n        // Write your solution here\n        return false;\n    }\n}` },
    expectedOutput: { javascript: "true", python: "True", java: "true" },
  },
  {
    title: "Find Minimum in Rotated Sorted Array",
    slug: "find-minimum-in-rotated-sorted-array",
    difficulty: "Medium",
    category: "Binary Search • Array",
    description: { text: "Find the minimum element in a rotated sorted array.", notes: ["The array is sorted in non-decreasing order and rotated."] },
    tags: ["binary-search", "arrays"],
    examples: [{ input: "nums = [4,5,6,7,0,1,2]", output: "0" }],
    constraints: ["1 ≤ nums.length ≤ 10⁵"],
    starterCode: { javascript: `function findMin(nums) {\n  // Write your solution here\n}`, python: `def findMin(nums):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static int findMin(int[] nums) {\n        // Write your solution here\n        return 0;\n    }\n}` },
    expectedOutput: { javascript: "0", python: "0", java: "0" },
  },
  {
    title: "Combination Sum",
    slug: "combination-sum",
    difficulty: "Medium",
    category: "Backtracking • Array",
    description: { text: "Return all unique combinations that sum to a target from a set of distinct candidates.", notes: ["Each candidate can be used once per combination."] },
    tags: ["backtracking", "arrays"],
    examples: [{ input: "candidates = [2,3,6,7], target = 7", output: "[[2,2,3],[7]]" }],
    constraints: ["1 ≤ candidates.length ≤ 30", "1 ≤ target ≤ 40"],
    starterCode: { javascript: `function combinationSum(candidates, target) {\n  // Write your solution here\n}`, python: `def combinationSum(candidates, target):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static List<List<Integer>> combinationSum(int[] candidates, int target) {\n        // Write your solution here\n        return new ArrayList<>();\n    }\n}` },
    expectedOutput: { javascript: "[[2,2,3],[7]]", python: "[[2,2,3],[7]]", java: "[[2,2,3],[7]]" },
  },
  {
    title: "Pacific Atlantic Water Flow",
    slug: "pacific-atlantic-water-flow",
    difficulty: "Medium",
    category: "Graph • DFS",
    description: { text: "Return cells that can flow to both the Pacific and Atlantic oceans by moving up, down, left, or right.", notes: ["Use reverse DFS from boundaries."] },
    tags: ["graph", "dfs", "grid"],
    examples: [{ input: "heights = [[1,2,2,3,5],[3,2,3,4,4],[2,4,5,3,1],[6,7,1,4,5],[5,1,1,2,4]]", output: "[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[3,2],[3,3],[3,4]]" }],
    constraints: ["The number of rows and columns is between 1 and 200."],
    starterCode: { javascript: `function pacificAtlantic(heights) {\n  // Write your solution here\n}`, python: `def pacificAtlantic(heights):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static List<List<Integer>> pacificAtlantic(int[][] heights) {\n        // Write your solution here\n        return new ArrayList<>();\n    }\n}` },
    expectedOutput: { javascript: "[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[3,2],[3,3],[3,4]]", python: "[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[3,2],[3,3],[3,4]]", java: "[[0,4],[1,3],[1,4],[2,2],[3,0],[3,1],[3,2],[3,3],[3,4]]" },
  },
  {
    title: "Subtree of Another Tree",
    slug: "subtree-of-another-tree",
    difficulty: "Easy",
    category: "Tree • Recursion",
    description: { text: "Determine whether a tree is a subtree of another tree.", notes: ["You can compare serialization or recursive checks."] },
    tags: ["trees", "recursion"],
    examples: [{ input: "root = [3,4,5,1,2], subRoot = [4,1,2]", output: "true" }],
    constraints: ["0 ≤ tree nodes ≤ 10⁵"],
    starterCode: { javascript: `function isSubtree(root, subRoot) {\n  // Write your solution here\n}`, python: `def isSubtree(root, subRoot):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static boolean isSubtree(TreeNode root, TreeNode subRoot) {\n        // Write your solution here\n        return false;\n    }\n}` },
    expectedOutput: { javascript: "true", python: "True", java: "true" },
  },
  {
    title: "Maximum Depth of Binary Tree",
    slug: "maximum-depth-of-binary-tree",
    difficulty: "Easy",
    category: "Tree • Recursion",
    description: { text: "Return the maximum depth of a binary tree.", notes: ["Depth is measured by number of nodes along the longest path."] },
    tags: ["trees", "recursion"],
    examples: [{ input: "root = [3,9,20,null,null,15,7]", output: "3" }],
    constraints: ["0 ≤ nodes ≤ 10⁴"],
    starterCode: { javascript: `function maxDepth(root) {\n  // Write your solution here\n}`, python: `def maxDepth(root):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static int maxDepth(TreeNode root) {\n        // Write your solution here\n        return 0;\n    }\n}` },
    expectedOutput: { javascript: "3", python: "3", java: "3" },
  },
  {
    title: "Implement Trie",
    slug: "implement-trie",
    difficulty: "Medium",
    category: "Trie • Hash Map",
    description: { text: "Implement a trie with insertion, search, and prefix matching methods.", notes: ["A trie is a tree of character nodes."] },
    tags: ["trie", "hashmap"],
    examples: [{ input: "['Trie','insert','search','startsWith']", output: "true" }],
    constraints: ["The number of operations is at most 10^4.", "Word lengths are at most 50."] ,
    starterCode: { javascript: `class Trie {\n  // Write your solution here\n}`, python: `class Trie:\n    # Write your solution here\n    pass`, java: `class Trie {\n    // Write your solution here\n}` },
    expectedOutput: { javascript: "true", python: "True", java: "true" },
  },
  {
    title: "Find K Closest Points",
    slug: "find-k-closest-points",
    difficulty: "Medium",
    category: "Heap • Sorting",
    description: { text: "Return the k closest points to the origin from a list of points.", notes: ["Use a heap or sorting strategy."] },
    tags: ["heap", "sorting"],
    examples: [{ input: "points = [[1,3],[-2,2]], k = 1", output: "[[-2,2]]" }],
    constraints: ["1 ≤ k ≤ points.length ≤ 10⁴"],
    starterCode: { javascript: `function kClosest(points, k) {\n  // Write your solution here\n}`, python: `def kClosest(points, k):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static int[][] kClosest(int[][] points, int k) {\n        // Write your solution here\n        return new int[0][0];\n    }\n}` },
    expectedOutput: { javascript: "[[-2,2]]", python: "[[-2, 2]]", java: "[[-2,2]]" },
  },
  {
    title: "Daily Temperatures",
    slug: "daily-temperatures",
    difficulty: "Medium",
    category: "Stack • Array",
    description: { text: "For each day, return the number of days you must wait before a warmer temperature appears.", notes: ["Use a monotonic stack."] },
    tags: ["stack", "arrays"],
    examples: [{ input: "temperatures = [73,74,75,71,69,72,76,73]", output: "[1,1,4,2,1,1,0,0]" }],
    constraints: ["1 ≤ temperatures.length ≤ 10⁵"],
    starterCode: { javascript: `function dailyTemperatures(temperatures) {\n  // Write your solution here\n}`, python: `def dailyTemperatures(temperatures):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static int[] dailyTemperatures(int[] temperatures) {\n        // Write your solution here\n        return new int[0];\n    }\n}` },
    expectedOutput: { javascript: "[1,1,4,2,1,1,0,0]", python: "[1, 1, 4, 2, 1, 1, 0, 0]", java: "[1,1,4,2,1,1,0,0]" },
  },
  {
    title: "Course Schedule II",
    slug: "course-schedule-ii",
    difficulty: "Medium",
    category: "Graph • Topological Sort",
    description: { text: "Return a correct order for taking courses given their prerequisite relation.", notes: ["Canonical topological ordering."] },
    tags: ["graph", "topological-sort"],
    examples: [{ input: "numCourses = 4, prerequisites = [[1,0],[2,0],[3,1],[3,2]]", output: "[0,2,1,3]" }],
    constraints: ["1 ≤ numCourses ≤ 2000"],
    starterCode: { javascript: `function findOrder(numCourses, prerequisites) {\n  // Write your solution here\n}`, python: `def findOrder(numCourses, prerequisites):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static int[] findOrder(int numCourses, int[][] prerequisites) {\n        // Write your solution here\n        return new int[0];\n    }\n}` },
    expectedOutput: { javascript: "[0,2,1,3]", python: "[0, 2, 1, 3]", java: "[0,2,1,3]" },
  },
  {
    title: "N-Queens",
    slug: "n-queens",
    difficulty: "Hard",
    category: "Backtracking • Matrix",
    description: { text: "Return all distinct solutions to the n-queens puzzle." , notes: ["Place one queen per row, check diagonal conflicts."] },
    tags: ["backtracking", "matrix"],
    examples: [{ input: "n = 4", output: "[['.Q..','...Q','Q...','..Q.'],['..Q.','Q...','...Q','.Q..']]" }],
    constraints: ["1 ≤ n ≤ 9"],
    starterCode: { javascript: `function solveNQueens(n) {\n  // Write your solution here\n}`, python: `def solveNQueens(n):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static List<List<String>> solveNQueens(int n) {\n        // Write your solution here\n        return new ArrayList<>();\n    }\n}` },
    expectedOutput: { javascript: "[['.Q..','...Q','Q...','..Q.'],['..Q.','Q...','...Q','.Q..']]", python: "[['.Q..','...Q','Q...','..Q.'],['..Q.','Q...','...Q','.Q..']]", java: "[[.Q..,...Q,Q...,..Q.],[..Q.,Q...,...Q,.Q..]]" },
  },
  {
    title: "All Paths from Source to Target",
    slug: "all-paths-from-source-to-target",
    difficulty: "Medium",
    category: "Graph • DFS",
    description: { text: "Return all possible paths from node 0 to node n - 1 in a directed acyclic graph.", notes: ["Use DFS and prune neighbor searches."] },
    tags: ["graph", "dfs"],
    examples: [{ input: "graph = [[1,2],[3],[3],[]]", output: "[[0,1,3],[0,2,3]]" }],
    constraints: ["2 ≤ graph.length ≤ 15"],
    starterCode: { javascript: `function allPathsSourceTarget(graph) {\n  // Write your solution here\n}`, python: `def allPathsSourceTarget(graph):\n    # Write your solution here\n    pass`, java: `class Solution {\n    public static List<List<Integer>> allPathsSourceTarget(int[][] graph) {\n        // Write your solution here\n        return new ArrayList<>();\n    }\n}` },
    expectedOutput: { javascript: "[[0,1,3],[0,2,3]]", python: "[[0,1,3],[0,2,3]]", java: "[[0,1,3],[0,2,3]]" },
  }
];

try {
  await connectDB();
  for (const problem of problems) {
    await Problem.findOneAndUpdate(
      { title: problem.title },
      { $set: problem },
      { upsert: true, new: true, runValidators: true, setDefaultsOnInsert: true }
    );
  }

  const count = await Problem.countDocuments();
  console.log(`Upserted ${problems.length} production interview questions. Total Problems: ${count}`);
  process.exit(0);
} catch (error) {
  console.error(error);
  process.exit(1);
}
